import assert from "node:assert/strict";
import test from "node:test";
import { toNetscapeCookies } from "../src/cookies.js";

test("converts cookies to Netscape cookie file format", () => {
  const output = toNetscapeCookies([
    {
      name: "session",
      value: "secret",
      domain: ".example.com",
      path: "/",
      expirationDate: 2_000_000_000.9,
      httpOnly: true,
      secure: true
    },
    { name: "theme", value: "dark", domain: "example.com" }
  ]);

  assert.equal(output, [
    "# Netscape HTTP Cookie File",
    "# Generated by CookieSync. Do not edit.",
    "",
    "#HttpOnly_.example.com\tTRUE\t/\tTRUE\t2000000000\tsession\tsecret",
    "example.com\tFALSE\t/\tFALSE\t0\ttheme\tdark",
    ""
  ].join("\n"));
});
