export function toNetscapeCookies(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by CookieSync. Do not edit.", ""];
  for (const cookie of cookies) {
    const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
    const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
    lines.push([
      domain,
      includeSubdomains,
      cookie.path || "/",
      cookie.secure ? "TRUE" : "FALSE",
      expires,
      cookie.name,
      cookie.value
    ].join("\t"));
  }
  return `${lines.join("\n")}\n`;
}
